# Generated by Django 5.0.1 on 2024-01-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='https://images.pexels.com/photos/7675398/pexels-photo-7675398.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', upload_to='images/'),
        ),
    ]
