# Generated by Django 5.0.1 on 2024-01-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=128)),
                ('linked_in', models.URLField(max_length=500)),
                ('github', models.URLField(max_length=500)),
                ('itch_io', models.URLField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
