# Generated by Django 5.0.1 on 2024-01-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
