# Generated by Django 5.0.1 on 2024-01-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_text_project_brief_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='location',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
    ]
